stages:
  split:
    cmd: |
      python src/data/split.py
        --input data/raw/raw.csv
        --out_dir data/processed
        --test_size ${split.test_size}
        --random_state ${split.random_state}
    deps:
      - src/data/split.py
      - data/raw/raw.csv
    params:
      - split.test_size
      - split.random_state
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: |
      python src/data/normalize.py
        --x_train data/processed/X_train.csv
        --x_test data/processed/X_test.csv
        --out_dir data/processed
        --method ${normalize.method}
        --scaler_path models/data/scaler.pkl
    deps:
      - src/data/normalize.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    params:
      - normalize.method
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - models/data/scaler.pkl

  gridsearch:
    cmd: |
      python src/models/grid_search.py
        --x_train data/processed/X_train_scaled.csv
        --y_train data/processed/y_train.csv
        --params params.yaml
        --out models/best_params.pkl
    deps:
      - src/models/grid_search.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - params.yaml
    outs:
      - models/best_params.pkl

  training:
    cmd: |
      python src/models/training.py
        --x_train data/processed/X_train_scaled.csv
        --y_train data/processed/y_train.csv
        --best_params models/best_params.pkl
        --model_out models/gbr_model.pkl
        --random_state ${training.random_state}
    deps:
      - src/models/training.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
    params:
      - training.random_state
    outs:
      - models/gbr_model.pkl

  evaluate:
    cmd: |
      python src/models/evaluate.py
        --x_test data/processed/X_test_scaled.csv
        --y_test data/processed/y_test.csv
        --model models/gbr_model.pkl
        --pred_out data/processed/prediction.csv
        --metrics_out metrics/scores.json
    deps:
      - src/models/evaluate.py
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/gbr_model.pkl
    outs:
      - data/processed/prediction.csv
    metrics:
      - metrics/scores.json
